<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Alert Type' => '',
  'Alerts' => '',
  'Automatic Reverse Location' => '',
  'Client  Name' => '',
  'Comment' => '',
  'Company  Logo' => '',
  'Company  Name' => '',
  'Contact Email' => '',
  'Contact info' => '',
  'Create New' => '',
  'Current Driver' => '',
  'Current Project' => '',
  'Data Source' => '',
  'Document Exp Date' => '',
  'Driver  Name' => '',
  'Driver Iqamaa' => '',
  'Driver License' => '',
  'Driver Photo' => '',
  'EQUAL(=)' => '',
  'Email' => '',
  'Emz Web Map' => '',
  'Enable Map Label' => '',
  'Enable Mobile Alert' => '',
  'Enable Web Alert' => '',
  'Enabled' => '',
  'Greater than(>)' => '',
  'Group Name' => '',
  'License Id' => '',
  'Max Vehicle Speed' => '',
  'Mobile  Number' => '',
  'Mobile Notfications' => '',
  'Monthly limits' => '',
  'Notes' => '',
  'Notess' => '',
  'Ping URL' => '',
  'Plate #' => '',
  'Project Name' => '',
  'Real Time' => '',
  'SMS' => '',
  'Select Datasource' => '',
  'Send To' => '',
  'Smaller than(<)' => '',
  'Start time' => '',
  'Type' => '',
  'Value' => '',
  'Weekly limits' => '',
  'Year of Make' => '',
  'end time' => '',
  'sub group' => '',
  'vehicle Color' => '',
  'vehicle Map Icon' => '',
  'vehicle Name' => '',
  'vehicle Number' => '',
  'vehicle Type' => '',
  'you can use ' => '',
);