<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '#' => '',
  'Alerts Report' => '',
  'All Datasources' => '',
  'All Project' => '',
  'All Vehicles' => '',
  'All Zones' => '',
  'CSV' => '',
  'DataSources Report  Setting' => '',
  'Distance  Setting' => '',
  'Distance Report' => '',
  'Distance Report Daily' => '',
  'Driver Logbook' => '',
  'Exel' => '',
  'Export' => '',
  'Filter by This vehicle' => '',
  'From' => '',
  'Geofence Report' => '',
  'Geofence Report  Setting' => '',
  'Group' => '',
  'Object  Setting' => '',
  'PDF' => '',
  'Project' => '',
  'Project Movement Report' => '',
  'ReLoad Report' => '',
  'Report Name' => '',
  'Select Datasource' => '',
  'Speed  Setting' => '',
  'Speed Report' => '',
  'To' => '',
  'TripStop Report' => '',
  'Vehicles Status Report' => '',
  'Working Vehicle/Time' => '',
    
    //reports
    "Number" => "Number",
    "Plate_number" => "Plate number",
    "vin" => "vin",
    "Distance" => "Distance",
    "Speed(min)" => "Speed(min)",
    
    
    "Engine_on_duration" => "Engine-on du.",
    
    'Idle_Count' => 'Idle (Count)', 
    'Engine_ON_Count' => 'Engine-On (Count)', 
    "First_Moving_date" => "First Moving date",
    "First_Moving_time" => "First Moving time",
    "Last_Moving_date" => "Last Moving date",
    "Last_Moving_time" => "Last Moving time",
    "First_Stop_date" => "First Stop date",
    "First_Stop_time" => "First Stop time",
    "Last_Stop_date" => "Last Stop date",
    "Last_Stop_time" => "Last Stop time",
    "Engine_off_days" => "Engine-off days",
    "Engine_on_duration" => "Engine-on duration",
    "Engine_idle_duration" => "Engine-idle duration",
    "Driving_duration" => "Driving duration",
    "Parking_duration" => "Parking duration",
    "Engine_ON_duration_max" => "Engine-On du. (max)",
    "Engine_ON_duration_min" => "Engine-On du. (min)",
    "Engine_ON_duration_avg" => "Engine-On du. (avg)",
    "Idle_duration_max" => "Idle duration (max)",
    "Idle_duration_min" => "Idle duration (min)",
    "Idle_duration_avg" => "Idle duration (avg)",
    "Parking_duration_max" => "Parking duration (max)",
    "Parking_duration_min" => "Parking duration (min)",
    "Parking_duration_avg" => "Parking duration (avg)",
    
    "Fuel_consumption" => "Fuel consumption",
    
    "Cost" => "Cost",
    "Engine_Utilisation" => "Engine Utilisation",
    
    "Work_Utilisation" => "Work Utilisation",
    
    "Date" => "Date",
     "Year" => "Year",
    "Week"=>"Week",
   "Month"=>"Month",
     "Day" => "Day",
    "Distance" => "Distance",
    "Beginning" => "Beginning",
    "End" => "End",
    "Duration" => "Duration",
     "engine_idle" => "Engine Idle",
    "engine_work" => "Engine Work",
    "Location" => "Location",
   "CITY" => "City",
     "Mileage" => "Mileage",
    "Sensor" => "Sensor",
   "value" => "value",
     "start_X" => "Start X",
    "start_Y" => "Start Y",
    "altitude" => "Altitude",
   "angle" => "Angle",
    "speed" => "Speed",
     "params" => "parameters",
    "event_text" => "Event Text",
    
    
    
    
    "Speed(Max)" =>  "Speed(Max)",
    "Speed(avg)" =>  "Speed(avg)",
    "X" => "X",
    "Y" => "Y",
    "Start_Location" => "Start Location",
    "Start_City" => "Start City",
    "End_Location" => "End Location",
    "End_City" => "End City",
    "Stop_duration_max" => "Stop duration (max)",
    "Stop_duration_min" => "Stop duration (min)",
    "Stop_duration_avg" => "Stop duration (avg)",
    "Idle_Duration" => "Idle Duration",
    "EngineState" => "Engine State",
    
    
    
 "In_movement" => "In_movement",
    "EngineOff" => "Engine Off",
    "Zone_Name" => "Zone Name",
   "Max_speed" => "Max speed",
    "Avg_speed" => "Avg speed",
     "Activation_Time" => "Activation Time",
    "Deactivation_Time" => "Deactivation Time",
   "Point_name" => "Point Name",
    "Arrival_time" => "Arrival time",
    "Arrival_location" => "Arrival location",
    
    "Date_MaxSpeed_Reached" => "Date of Max Speed",
   "end_X" => "End X",
    "end_Y" => "End Y",
    "event_desc" => "Event description",
"dt_server" => "Server Date",
    "dt_tracker" => "Tracker Date",
    "Previous_job" => "Previous job",
    "Current_Job" => "Current Job",
     "Action_Time" => "Action Time",
    "Route" => "Route",
    "Schedule" => "Schedule",
    "Round"=>"Round",
   "Round_code" => "Round code",
    "Initial_location" => "Initial location",
    "Result" => "Result",
    "Order" => "Order",
    "Total_points" => "Total points",
    "Skipped_points" => "Skipped points",
    "Visited_points" => "Visited points",
    "Early_visits" => "Early visits",
     "late_visits" => "late visits",
    "Departure_time" => "Departure time",
   "Departure_location" => "Departure location",
    "Departure_time_deviation" => "Departure T. deviation",
    "Presence_duration" => "Presence duration",
    "Presence_mileage" => "Presence mileage",
    "Section_time" => "Section time",
     "Section_mileage" => "Section mileage",
   "Notes" => "Notes",
    "Sender" => "Sender",
    "Text" => "Text",
    "TimeStamp" => "TimeStamp",
    "Device_No" => "Device No",
     "Sent_By" => "Sent By",
   "Command_name" => "Command name",
   "Command_type" => "Command type",
    "Parameters" => "Parameters",
     "Execution_time" => "Execution time",
   "IsSent" => "Is Sent?",
     "Client" => "Client",
    "SerialNumber" => "Serial Number",
    
    "Imei" => "IMEI",
    "GsmNumber" => "GSM Number",
    "SimCardSn" => "SIM Card SerialNumber",
    "SinceDate" => "Since Date",
    "SinceDateText" => "Since Date Text",
   "GpsTime" => "GPS Time",
    "GpsTimeText" => "GPS Time Text",
   "TypeId" => "Type Id",
    "Name" => "Name",
    "Reader_Result" => "Reader Result",
    
    "departure_X" => "Departure X",
    "departure_Y" => "Departure Y",
    "arrival_X" => "Arrival X",
    "arrival_Y" => "Arrival Y",
    
        //Driver
    
    "GsmNumber" => "GSM Number",

    "Driver" => "Driver",
"Sender" => "Sender",
    "Text" => "Text",
   "TimeStamp" => "TimeStamp",
    "Started" => "Started",
      "Ended" => "Ended",
    "BindType" => "Bind Type",
     "on_time" => "On Time",
     "idle_time" => "Idle Time",
     "off_time" => "Off Time",
    
    
    // geo-fences
    "Time_In" => "Time In",
    "Time_Out" => "Time Out",
    "Duration_In" => "Duration In",
    
);
