<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '#' => '',
  'Alerts Report' => '',
  'All Datasources' => '',
  'All Project' => '',
  'All Vehicles' => '',
  'All Zones' => '',
  'CSV' => '',
  'DataSources Report  Setting' => '',
  'Distance  Setting' => '',
  'Distance Report' => '',
  'Distance Report Daily' => '',
  'Driver Logbook' => '',
  'Exel' => '',
  'Export' => '',
  'Filter by This vehicle' => '',
  'From' => '',
  'Geofence Report' => '',
  'Geofence Report  Setting' => '',
  'Group' => '',
  'Object  Setting' => '',
  'PDF' => '',
  'Project' => '',
  'Project Movement Report' => '',
  'ReLoad Report' => '',
  'Report Name' => '',
  'Select Datasource' => '',
  'Speed  Setting' => '',
  'Speed Report' => '',
  'To' => '',
  'TripStop Report' => '',
  'Vehicles Status Report' => '',
  'Working Vehicle/Time' => '',
    
    
    //reports
    "Number" => "رقم",
    "Plate_number" => "رقم اللوحة",
    "vin" => "رقم التعريف للمركبة",
    "Distance" => "المسافة",
    "Speed(min)" => "السرعة الدنيا ",
    
    "First_Stop_Time" => "رقم ",
    "Last_Stop_Time" => "رقم ",
    "Engine_off_days" => "رقم ",
    
    "Engine_on_duration" => "فترة التشغيل",
    
    'Idle_Count' => 'عداد الخمول', 
    'Engine_ON_Count' => 'عداد عمل المحرك', 
    "First_Moving_date" => "تاريخ بداية التحرك",
    "First_Moving_time" => "وقت بداية التحرك",
    "Last_Moving_date" => "تاريخ نهاية التحرك",
    "Last_Moving_time" => "وقت نهاية التحرك",
    "First_Stop_date" => "وقت اول ايقاف",
    "First_Stop_time" => "تاريخ اول ايقاف",
    "Last_Stop_date" => "وقت اخر ايقاف",
    "Last_Stop_time" => "تاريخ اخر ايقاف",
    "Engine_off_days" => "ايام ايقاف المحرك",
    "Engine_on_duration" => "مدة تشغيل المحرك",
    "Engine_idle_duration" => "مدة تعليق المحرك",
    "Driving_duration" => "مدة القيادة",
    "Parking_duration" => "مدة الايقاف المؤقت",
    "Engine_ON_duration_max" => "اقصي مدة تشغيل",
    "Engine_ON_duration_min" => "ادني مدة تشغيل",
    "Engine_ON_duration_avg" => "متوسط مدة التشغيل",
    "Idle_duration_max" => "اقصي مدة تعليق",
    "Idle_duration_min" => "ادني مدة تعليق",
    "Idle_duration_avg" => "متوسط مدة التعليق",
    "Parking_duration_max" => "اقصي مدة توقف",
    "Parking_duration_min" => "ادني مدة توقف",
    "Parking_duration_avg" => "متوسط مدة التوقف",
    
    "Fuel_consumption" => "استهلاك الوقود",
    
    "Cost" => "تكلفة",
    "Engine_Utilisation" => "استخدام المحرك",
    
    "Work_Utilisation" => "استخدام العمل",
    
    "Date" => "التاريخ",
     "Year" => "العام",
    "Week"=>"اسبوع",
   "Month"=>"شهر",
     "Day" => "اليوم",
    "Distance" => "المسافة",
    "Beginning" => "البداية",
    "End" => "النهاية",
    "Duration" => "مدة",
     "engine_idle" => "المحرك خامل",
    "engine_work" => "المحرك يعمل",
    "Location" => "الموقع",
   "CITY" => "مدينة",
     "Mileage" => "عدد الأميال",
    "Sensor" => "جهاز استشعار",
   "value" => "القيمة",
     "start_X" => "X البداية",
    "start_Y" => "Y البداية",
    "altitude" => "ارتفاع",
   "angle" => "زاوية",
    "speed" => "السرعة",
     "params" => "متغيرات",
    "event_text" => "نص الحدث",
    
    
    
    
    "Speed(Max)" =>  "السرعة القصوى",
    "Speed(avg)" =>  "السرعة المتوسطة",
    "X" => "X",
    "Y" => "Y",
    "Start_Location" => "موقع البداية",
    "Start_City" => "مدينة البداية",
    "End_Location" => "موقع النهاية",
    "End_City" => "مدينة النهاية",
    "Stop_duration_max" => "اكبر مدة التوقف",
    "Stop_duration_min" => "اقل مدة التوقف",
    "Stop_duration_avg" => "متوسط مدة التوقف",
    "Idle_Duration" => "مدة السكون",
    "EngineState" => "حالة المحرك",
    
    
    
 "In_movement" => "متحركة",
    "EngineOff" => "المحرك متوقف",
    "Zone_Name" => "اسم المنطقة",
   "Max_speed" => "السرعة القصوى",
    "Avg_speed" => "متوسط السرعة ",
     "Activation_Time" => "وقت التفعيل",
    "Deactivation_Time" => "وقع التعطيل",
   "Point_name" => "اسم النقطة",
    "Arrival_time" => "وقت الوصول",
    "Arrival_location" => "موقع الوصول",
    
    "Date_MaxSpeed_Reached" => "تاريخ السرعة القصوى",
   "end_X" => "النهاية X",
    "end_Y" => "النهاية Y",
    "event_desc" => "وصف الحدث",
"dt_server" => "وقت الخادم",
    "dt_tracker" => "وقت الجهاز",
    "Previous_job" => "العمل السابق",
    "Current_Job" => "العمل الحالي",
     "Action_Time" => "وقت العمل",
    "Route" => "المسار",
    "Schedule" => "الجدول الزمني",
    "Round"=>"جولة",
   "Round_code" => "رقم الطريق",
    "Initial_location" => "المكان الابتدائي",
    "Result" => "النتيجة",
    "Order" => "أمر",
    "Total_points" => "مجموع النقاط",
    "Skipped_points" => "النقاط المختطية",
    "Visited_points" => "تم زيارتها",
    "Early_visits" => "زيارات باكرة",
     "late_visits" => "زيارات متأخرة",
    "Departure_time" => "وقت المغادرة",
   "Departure_location" => "موقع المغادرة",
    "Departure_time_deviation" => "اختلاف موعد المغادرة",
    "Presence_duration" => "مدة التواجد",
    "Presence_mileage" => "عدد كيلومترات التواجد",
    "Section_time" => "وقت القسم ",
     "Section_mileage" => "عدد اميال القسم",
   "Notes" => "ملاحظات",
    "Sender" => "المرسل ",
    "Text" => "النص",
    "TimeStamp" => "الطابع الزمني",
    "Device_No" => "رقم الجهاز",
     "Sent_By" => "مرسل بواسطة",
   "Command_name" => "اسم الامر",
   "Command_type" => "نوع الامر",
    "Parameters" => "المعاملات",
     "Execution_time" => "وقت التنفيذ",
   "IsSent" => "تم الارسال ",
     "Client" => "عميل",
    "SerialNumber" => "الرقم التسلسلي ",
    
    "Imei" => "IMEI",
    "GsmNumber" => "رقم الجوال",
    "SimCardSn" => "رقم الشريحة التسلسلي",
    "SinceDate" => "منذ تاريخ",
    "SinceDateText" => "منذ تاريخ النص",
   "GpsTime" => "توقيت الـ GPS",
    "GpsTimeText" => "وقت نص الGPS",
   "TypeId" => "رقم النوع",
    "Name" => "الاسم",
    "Reader_Result" => "النتيجة القارئ",
    
    "departure_X" => "نقطة مغادرة X",
    "departure_Y" => "نقطة المغادرة Y",
    "arrival_X" => "نقطة الوصول X",
    "arrival_Y" => "نقطة الوصول Y",
    
    
    
    //Driver
    
    "GsmNumber" => "رقم الجوال",

    "Driver" => "السائق",
"Sender" => "المرسل ",
    "Text" => "النص",
   "TimeStamp" => "الطابع الزمني",
    "Started" => "تم البدأ",
      "Ended" => "تم الانتهاء",
    "BindType" => "نوع الارتباط",
     "on_time" => "وقت التشغيل",
     "idle_time" => "وقت السكون",
     "off_time" => "وقت الاغلاق",
    
    
    // geo-fences
    "Time_In" => "وقت الدخول",
    "Time_Out" => "وقت الخروج",
    "Duration_In" => "مدة الدخول",
    
    
    
);
